package jumpin.exception;

import java.util.List;

import jumpin.common.Position;
import jumpin.element.GameElement;

public class IllegalMoveException extends IllegalArgumentException {

	/**
	 * Auto-generated by Eclipse.
	 */
	private static final long serialVersionUID = 3280959467427523853L;

	private final GameElement element;
	private final Position position;
	private final List<Position> validPositions;

	public IllegalMoveException(final GameElement element, final Position position, final List<Position> validPositions) {
		this.element = element;
		this.position = position;
		this.validPositions = validPositions;
	}

	@Override
	public String getMessage() {
		return String.format("Moving %s to position %s is illegal. Here are the valid moves: %s",
				element.getFriendlyId(), position, validPositions);
	}
}
