package jumpin.common;

/**
*  Position
*  The Position class is meant to create all the spaces that can be accessed on the board.
*  These spaces are marked by a row and column value in the 5 by 5 grid, with the initial row
*  and column starting at 0 and going to 4, and each position is created with two values as [1,2].
*  Used by all the elements in the board, as well as the Spots, Hills and Holes.
*/
public class Position {
	private final int row;
	private final int column;
	
	/**
	*  Creates the position object taking in the row and column values.
	*  @param row
	*  @param column
	*/
	public Position (int row, int column) {
		this.row = row;
		this.column = column;
	}

	/**
	*  Returns the row of the position object
	*  @return row
	*/
	public int getRow() {
		return row;
	}

	/**
	*  Returns the column of the position object
	*  @return column
	*/
	public int getColumn() {
		return column;
	}

	/**
	*  Creates the formatted version of the Position as [a, b].
	* @return String
	*/
	@Override
	public String toString() {
		return String.format("[%s, %s]", row, column);
	}

	// Auto-generated by Eclipse
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + column;
		result = prime * result + row;
		return result;
	}

	// Auto-generated by Eclipse
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Position other = (Position) obj;
		if (column != other.column)
			return false;
		if (row != other.row)
			return false;
		return true;
	}
	
}
