package jumpin.exception;

public class NoPossibleSolutionException extends IllegalArgumentException {

	private static final long serialVersionUID = -1676455433355799859L; // Auto-generated by Eclipse

	public NoPossibleSolutionException(final String message) {
		super(message);
	}
}
